import React, { createContext, useContext, useState, useEffect } from 'react';
import { User, LoginRequest, RegisterRequest, AuthContextType } from '../types/auth';
import api from '../lib/api';
import { demoUsers } from '../data/demoData';

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Check if user is already logged in
    const token = localStorage.getItem('authToken');
    if (token) {
      // You might want to validate the token with the backend here
      setLoading(false);
    } else {
      setLoading(false);
    }
  }, []);

  const login = async (credentials: LoginRequest) => {
    try {
      // For demo purposes, simulate login with demo users
      const demoUser = Object.values(demoUsers).find(user => user.email === credentials.email);
      if (demoUser && credentials.password === 'demo123') {
        localStorage.setItem('authToken', 'authenticated');
        setUser(demoUser);
      } else {
        // Try actual API call as fallback
        const response = await api.post('/auth/signin', credentials);
        if (response.status === 200) {
          localStorage.setItem('authToken', 'authenticated');
          setUser({
            id: 1,
            name: 'User',
            email: credentials.email,
            phone: '',
            role: 'citizen',
            location: {
              type: 'Point',
              coordinates: [0, 0] // Default location
            }
          });
        }
      }
    } catch (error) {
      throw new Error('Login failed');
    }
  };

  const register = async (userData: RegisterRequest) => {
    try {
      console.log('Registering user with location:', userData.location);
      console.log('User data:', userData);
      
      // Make API call to backend
      const response = await api.post('/auth/signup', userData);
      console.log('Response:', response);
      
      if (response.status === 200) {
        // Backend generates ID and returns user data
        const userResponse = response.data;
        localStorage.setItem('authToken', 'authenticated');
        setUser({
          id: userResponse.id, // ID generated by backend
          name: userResponse.name,
          email: userResponse.email,
          phone: userResponse.phone,
          role: userResponse.role,
          location: userResponse.location
        });
      }
    } catch (error) {
      console.error('Registration error:', error);
      throw new Error('Registration failed');
    }
  };

  const logout = () => {
    localStorage.removeItem('authToken');
    setUser(null);
  };

  const value: AuthContextType = {
    user,
    login,
    register,
    logout,
    loading
  };

  return (
    <AuthContext.Provider value={value}>
      {children}
    </AuthContext.Provider>
  );
};
